version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eqgnJtGtfDbJtzr6jX8H8mB3B6FXrKyohDThMjrT
    volumes: 
      - cache:/data

volumes:
  dbdata6:
  cache:
    driver: local